# Generated by Django 3.2.5 on 2021-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restcountries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restcountry',
            name='alphacode2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='capital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='flag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='languages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='neighbours',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restcountry',
            name='timezone',
            field=models.TextField(),
        ),
    ]
